### ISSUE TITLE
issue in ms dos

### ISSUE THREAD

**Issue by preciouscoder** [RiseVision/rise-react-wallet#219]
After run wallet

(node:8752) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_connection' of undefined
    at domContentLoaded_.data (C:\snapshot\desktop\node_modules\carlo\lib\carlo.js:424:27)
    at Rpc.createWorld (C:\snapshot\desktop\node_modules\carlo\rpc\rpc.js:164:5)
    at Window.domContentLoaded_ (C:\snapshot\desktop\node_modules\carlo\lib\carlo.js:430:35)
    at Page.emit (events.js:182:13)
    at CDPSession.constructor.client.on.event (C:\snapshot\desktop\node_modules\puppeteer-core\lib\Page.js:131:58)
    at CDPSession.emit (events.js:182:13)
    at CDPSession._onMessage (C:\snapshot\desktop\node_modules\puppeteer-core\lib\Connection.js:216:12)
    at Connection._onMessage (C:\snapshot\desktop\node_modules\puppeteer-core\lib\Connection.js:99:19)
    at PipeTransport._dispatch (C:\snapshot\desktop\node_modules\puppeteer-core\lib\PipeTransport.js:59:22)
    at Socket.constructor._eventListeners.helper.addEventListener.buffer (C:\snapshot\desktop\node_modules\puppeteer-core\lib\PipeTransport.js:30:64)
(node:8752) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8752) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by TobiaszCudnik** [comment]
Looks like an issue with Chrome / Chromium. Can you please check which version do you have installed? The lowest supported is 70, thanks.

As a workaround you can install the web wallet to desktop when in chrome / chromium via top right menu -> Install Rise Wallet.

**Comment by preciouscoder** [comment]
Version 72.0.3626.109 (Official Build) (64-bit)
